(function() {
  const DS = window.CaromChampsDesignSystem_c6f88d;
  const Icon = window.CCIcon;
  const D = window.CCData;
  const { Card, DataTable, StatusBadge, Tag, Button, IconButton, Avatar, KpiCard } = DS;
  function PlanillasIA() {
    return /* @__PURE__ */ React.createElement("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, alignItems: "start" } }, /* @__PURE__ */ React.createElement(Card, { title: "Importaci\xF3n inteligente", subtitle: "Lee planillas en PDF o imagen con IA / OCR" }, /* @__PURE__ */ React.createElement("div", { style: { border: "2px dashed var(--cc-blue-200)", borderRadius: "var(--cc-radius-lg)", background: "var(--cc-blue-50)", padding: "34px 20px", textAlign: "center" } }, /* @__PURE__ */ React.createElement("div", { style: { display: "inline-flex", padding: 14, borderRadius: "50%", background: "#fff", color: "var(--cc-azul-mesa)", boxShadow: "var(--cc-shadow-sm)" } }, /* @__PURE__ */ React.createElement(Icon, { name: "upload", size: 26 })), /* @__PURE__ */ React.createElement("div", { style: { fontWeight: 600, fontSize: 15, marginTop: 12 } }, "Arrastra la planilla aqu\xED"), /* @__PURE__ */ React.createElement("div", { style: { fontSize: 13, color: "var(--cc-text-muted)", marginTop: 4 } }, "PDF, JPG o PNG \xB7 hasta 10 MB"), /* @__PURE__ */ React.createElement("div", { style: { marginTop: 14, display: "inline-block" } }, /* @__PURE__ */ React.createElement(Button, { variant: "primary", leftIcon: /* @__PURE__ */ React.createElement(Icon, { name: "scan-line", size: 16 }) }, "Seleccionar archivo"))), /* @__PURE__ */ React.createElement("div", { style: { marginTop: 16, display: "flex", flexDirection: "column", gap: 10 } }, [["Planilla_GrupoA_M1.pdf", "success", "Procesada"], ["Planilla_GrupoB_M3.jpg", "warning", "Requiere revisi\xF3n"], ["Planilla_GrupoB_M4.pdf", "active", "Procesando"]].map(([f, s, l], i) => /* @__PURE__ */ React.createElement("div", { key: i, style: { display: "flex", alignItems: "center", gap: 12, padding: "10px 12px", border: "1px solid var(--cc-border)", borderRadius: "var(--cc-radius-md)" } }, /* @__PURE__ */ React.createElement(Icon, { name: "file-text", size: 18, color: "var(--cc-azul-mesa)" }), /* @__PURE__ */ React.createElement("span", { style: { fontSize: 13.5, fontWeight: 500 } }, f), /* @__PURE__ */ React.createElement("span", { style: { marginLeft: "auto" } }, /* @__PURE__ */ React.createElement(StatusBadge, { status: s }, l)))))), /* @__PURE__ */ React.createElement(
      Card,
      {
        title: "Resultado detectado",
        subtitle: "Planilla_GrupoB_M3.jpg",
        actions: /* @__PURE__ */ React.createElement(Tag, { variant: "brand" }, /* @__PURE__ */ React.createElement(Icon, { name: "sparkles", size: 13 }), " IA \xB7 92%")
      },
      /* @__PURE__ */ React.createElement("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 } }, [["Local", "L\xE9a Dubois", true], ["Visitante", "Carlos Ruiz", true], ["Carambolas L", "33", true], ["Carambolas V", "31", false], ["Entradas", "30", true], ["Mayor serie", "5", true]].map(([k, v, ok], i) => /* @__PURE__ */ React.createElement("div", { key: i, style: { padding: "10px 12px", border: "1px solid var(--cc-border)", borderRadius: "var(--cc-radius-md)", background: ok ? "var(--cc-surface-card)" : "var(--cc-warning-soft)" } }, /* @__PURE__ */ React.createElement("div", { style: { fontSize: 11, letterSpacing: ".04em", textTransform: "uppercase", color: "var(--cc-text-muted)" } }, k), /* @__PURE__ */ React.createElement("div", { style: { display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 3 } }, /* @__PURE__ */ React.createElement("span", { style: { fontWeight: 600, fontSize: 15 } }, v), /* @__PURE__ */ React.createElement(Icon, { name: ok ? "check" : "pencil", size: 15, color: ok ? "var(--cc-verde-exito)" : "var(--cc-naranja-accion)" }))))),
      /* @__PURE__ */ React.createElement("div", { style: { marginTop: 16, padding: "12px 14px", background: "var(--cc-warning-soft)", borderRadius: "var(--cc-radius-md)", fontSize: 13, color: "var(--cc-state-warning)", display: "flex", gap: 8, alignItems: "center" } }, /* @__PURE__ */ React.createElement(Icon, { name: "scan-line", size: 16 }), " Un campo con baja confianza requiere validaci\xF3n manual."),
      /* @__PURE__ */ React.createElement("div", { style: { display: "flex", gap: 10, marginTop: 16 } }, /* @__PURE__ */ React.createElement(Button, { variant: "success", block: true, leftIcon: /* @__PURE__ */ React.createElement(Icon, { name: "check", size: 16 }) }, "Validar e importar"), /* @__PURE__ */ React.createElement(Button, { variant: "warning", leftIcon: /* @__PURE__ */ React.createElement(Icon, { name: "rotate-ccw", size: 16 }) }, "Reprocesar"))
    ));
  }
  function Llaves() {
    const b = D.bracket;
    const Match = ({ pair, winner }) => /* @__PURE__ */ React.createElement("div", { style: { background: "var(--cc-surface-card)", border: "1px solid var(--cc-border)", borderRadius: "var(--cc-radius-md)", overflow: "hidden", width: 188, boxShadow: "var(--cc-shadow-xs)" } }, pair.map((p, i) => {
      const win = winner === p;
      return /* @__PURE__ */ React.createElement("div", { key: i, style: { display: "flex", alignItems: "center", gap: 8, padding: "9px 12px", borderTop: i ? "1px solid var(--cc-border)" : "none", background: win ? "var(--cc-blue-50)" : "transparent" } }, /* @__PURE__ */ React.createElement(Avatar, { name: p, size: "xs" }), /* @__PURE__ */ React.createElement("span", { style: { fontSize: 13, fontWeight: win ? 700 : 500, color: win ? "var(--cc-azul-mesa)" : "var(--cc-text)" } }, p), win ? /* @__PURE__ */ React.createElement(Icon, { name: "check", size: 14, color: "var(--cc-azul-mesa)", style: { marginLeft: "auto" } }) : null);
    }));
    const Col = ({ label, children }) => /* @__PURE__ */ React.createElement("div", { style: { display: "flex", flexDirection: "column", justifyContent: "space-around", gap: 18 } }, /* @__PURE__ */ React.createElement("div", { style: { fontSize: 11, letterSpacing: ".08em", textTransform: "uppercase", color: "var(--cc-text-muted)", fontWeight: 700, textAlign: "center" } }, label), children);
    return /* @__PURE__ */ React.createElement(
      Card,
      {
        title: "Llaves eliminatorias",
        subtitle: "Cuadro final \xB7 8 jugadores",
        actions: /* @__PURE__ */ React.createElement(Button, { variant: "secondary", size: "sm", leftIcon: /* @__PURE__ */ React.createElement(Icon, { name: "download", size: 16 }) }, "Exportar bracket")
      },
      /* @__PURE__ */ React.createElement("div", { style: { display: "flex", gap: 40, padding: "8px 4px", overflowX: "auto" } }, /* @__PURE__ */ React.createElement(Col, { label: "Cuartos" }, b.qf.map((p, i) => /* @__PURE__ */ React.createElement(Match, { key: i, pair: p, winner: b.sf.flat().includes(p[0].split(" ").slice(-1)[0]) ? p[0] : p[0] }))), /* @__PURE__ */ React.createElement(Col, { label: "Semifinal" }, b.sf.map((p, i) => /* @__PURE__ */ React.createElement(Match, { key: i, pair: p, winner: p[0] }))), /* @__PURE__ */ React.createElement(Col, { label: "Final" }, b.final.map((p, i) => /* @__PURE__ */ React.createElement(Match, { key: i, pair: p, winner: b.champion }))), /* @__PURE__ */ React.createElement(Col, { label: "Campe\xF3n" }, /* @__PURE__ */ React.createElement("div", { style: { background: "var(--cc-gradient-deep)", borderRadius: "var(--cc-radius-lg)", padding: "20px 18px", width: 188, textAlign: "center", color: "#fff" } }, /* @__PURE__ */ React.createElement(Icon, { name: "trophy", size: 30, color: "var(--cc-amarillo-carambola)" }), /* @__PURE__ */ React.createElement("div", { style: { fontWeight: 700, fontSize: 16, marginTop: 8 } }, b.champion), /* @__PURE__ */ React.createElement("div", { style: { fontSize: 12, color: "var(--cc-gris-tecnico)", marginTop: 2 } }, "Campe\xF3n del torneo"))))
    );
  }
  function Reportes() {
    const reports = [
      ["Acta final del campeonato", "file-text", "Documento oficial de cierre", "Institucional"],
      ["Reporte 5 \xB7 Resultados", "bar-chart", "Posiciones finales por grupo", "Avanzado"],
      ["Ranking acumulado", "trophy", "Promedios e hist\xF3rico por jugador", "Federativo"],
      ["Bracket eliminatorio", "git-merge", "Cuadro final con resultados", "PDF"]
    ];
    return /* @__PURE__ */ React.createElement("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, alignItems: "start" } }, /* @__PURE__ */ React.createElement(Card, { title: "Reportes disponibles", subtitle: "Listos para exportar" }, /* @__PURE__ */ React.createElement("div", { style: { display: "flex", flexDirection: "column", gap: 10 } }, reports.map(([t, ic, sub, tag], i) => /* @__PURE__ */ React.createElement("div", { key: i, style: { display: "flex", alignItems: "center", gap: 12, padding: "12px 14px", border: "1px solid var(--cc-border)", borderRadius: "var(--cc-radius-md)" } }, /* @__PURE__ */ React.createElement("span", { style: { display: "inline-flex", padding: 9, borderRadius: 10, background: "var(--cc-blue-50)", color: "var(--cc-azul-mesa)" } }, /* @__PURE__ */ React.createElement(Icon, { name: ic, size: 18 })), /* @__PURE__ */ React.createElement("div", { style: { minWidth: 0 } }, /* @__PURE__ */ React.createElement("div", { style: { fontWeight: 600, fontSize: 14 } }, t), /* @__PURE__ */ React.createElement("div", { style: { fontSize: 12.5, color: "var(--cc-text-muted)" } }, sub)), /* @__PURE__ */ React.createElement("span", { style: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 8 } }, /* @__PURE__ */ React.createElement(Tag, null, tag), /* @__PURE__ */ React.createElement(IconButton, { label: "Descargar" }, /* @__PURE__ */ React.createElement(Icon, { name: "download", size: 18 }))))))), /* @__PURE__ */ React.createElement(
      Card,
      {
        variant: "marfil",
        title: "Acta final",
        subtitle: "Vista previa institucional",
        actions: /* @__PURE__ */ React.createElement(Button, { variant: "primary", size: "sm", leftIcon: /* @__PURE__ */ React.createElement(Icon, { name: "printer", size: 16 }) }, "Emitir")
      },
      /* @__PURE__ */ React.createElement("div", { style: { background: "#fff", borderRadius: "var(--cc-radius-md)", border: "1px solid var(--cc-border)", padding: 22 } }, /* @__PURE__ */ React.createElement("div", { style: { display: "flex", alignItems: "center", gap: 10, borderBottom: "2px solid var(--cc-azul-mesa)", paddingBottom: 12, marginBottom: 14 } }, /* @__PURE__ */ React.createElement("img", { src: "../../assets/logo-mark.png", alt: "", style: { height: 30 } }), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { style: { fontFamily: "var(--cc-font-display)", fontWeight: 800, fontSize: 15, color: "var(--cc-azul-profundo)" } }, "Copa Nacional 3 Bandas 2026"), /* @__PURE__ */ React.createElement("div", { style: { fontSize: 11.5, color: "var(--cc-text-muted)" } }, "Acta oficial de cierre \xB7 Club Billar Bogot\xE1"))), /* @__PURE__ */ React.createElement("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 14 } }, /* @__PURE__ */ React.createElement(KpiCard, { label: "Campe\xF3n", value: "Juan P\xE9rez", accent: "primary", icon: /* @__PURE__ */ React.createElement(Icon, { name: "trophy" }) }), /* @__PURE__ */ React.createElement(KpiCard, { label: "Mejor promedio", value: "1.428", accent: "success", icon: /* @__PURE__ */ React.createElement(Icon, { name: "target" }) })), /* @__PURE__ */ React.createElement(
        DataTable,
        {
          striped: false,
          hover: false,
          columns: [
            { key: "pos", header: "#", width: "40px", render: (v) => /* @__PURE__ */ React.createElement("span", { className: "cc-table__rank" }, v) },
            { key: "jugador", header: "Jugador", strong: true },
            { key: "avg", header: "AVG", align: "right" }
          ],
          rows: D.standings.slice(0, 4)
        }
      ))
    ));
  }
  function Cierre() {
    const steps = [["Todas las partidas finalizadas", true], ["Planillas validadas", true], ["Posiciones confirmadas", true], ["Llaves cerradas", true], ["Acta final revisada", false]];
    const ready = steps.every(([, d]) => d);
    return /* @__PURE__ */ React.createElement("div", { style: { display: "grid", gridTemplateColumns: "1fr 380px", gap: 16, alignItems: "start" } }, /* @__PURE__ */ React.createElement(Card, { title: "Cierre del campeonato", subtitle: "Validaci\xF3n final antes de emitir el acta" }, /* @__PURE__ */ React.createElement("div", { style: { display: "flex", flexDirection: "column" } }, steps.map(([t, done], i) => /* @__PURE__ */ React.createElement("div", { key: i, style: { display: "flex", alignItems: "center", gap: 12, padding: "13px 0", borderBottom: i < steps.length - 1 ? "1px solid var(--cc-border)" : "none" } }, /* @__PURE__ */ React.createElement("span", { style: { display: "inline-flex", color: done ? "var(--cc-verde-exito)" : "var(--cc-gris-tecnico)" } }, /* @__PURE__ */ React.createElement(Icon, { name: done ? "circle-check" : "circle-dot", size: 20 })), /* @__PURE__ */ React.createElement("span", { style: { fontSize: 14.5, fontWeight: 500, color: done ? "var(--cc-text)" : "var(--cc-text-muted)" } }, t), /* @__PURE__ */ React.createElement("span", { style: { marginLeft: "auto" } }, done ? /* @__PURE__ */ React.createElement(StatusBadge, { status: "success", dot: false }) : /* @__PURE__ */ React.createElement(StatusBadge, { status: "pending", dot: false })))))), /* @__PURE__ */ React.createElement(Card, { variant: "dark", title: "Estado del torneo", subtitle: "Listo para cierre formal" }, /* @__PURE__ */ React.createElement("div", { style: { display: "flex", flexDirection: "column", gap: 14 } }, /* @__PURE__ */ React.createElement("div", { style: { display: "flex", alignItems: "center", gap: 12, padding: "14px 16px", background: "rgba(245,193,22,.12)", borderRadius: "var(--cc-radius-md)" } }, /* @__PURE__ */ React.createElement(Icon, { name: "shield-check", size: 22, color: "var(--cc-amarillo-carambola)" }), /* @__PURE__ */ React.createElement("span", { style: { fontSize: 13.5, color: "var(--cc-blanco-marfil)" } }, "4 de 5 validaciones completas. Revisa el acta final para cerrar.")), /* @__PURE__ */ React.createElement(Button, { variant: ready ? "success" : "warning", block: true, leftIcon: /* @__PURE__ */ React.createElement(Icon, { name: "flag", size: 16 }) }, ready ? "Cerrar campeonato" : "Revisar acta final"), /* @__PURE__ */ React.createElement(Button, { variant: "ghost", block: true, style: { color: "var(--cc-gris-tecnico)" } }, "Reabrir fase anterior"))));
  }
  window.CCScreens = Object.assign(window.CCScreens || {}, { PlanillasIA, Llaves, Reportes, Cierre });
})();
